/**
 * Curated Chinese names for CLUBS across the club competitions tracked by
 * lib/daily-fetcher.ts (domestic leagues, continental club cups, and major
 * domestic cups). National-team competitions use lib/team-names-cn.ts
 * instead — see clubNameCn vs teamNameCn.
 *
 * Keyed by ESPN's `team.displayName` — a flat map, since the same club (e.g.
 * Real Madrid) appears under many different competition codes and should
 * resolve to one name everywhere. A small override map handles the rare case
 * where an identical name means a genuinely different club in different
 * competitions (Brazil's Santos vs. Mexico's Santos Laguna; England's
 * Liverpool vs. Uruguay's Liverpool in the Copa Libertadores).
 *
 * CSL entries are each club's native Chinese name (not a translation).
 * Everything else uses the name in common use by Chinese-language football
 * media.
 *
 * Coverage: full rosters for every domestic league, plus the Champions
 * League / Europa League / AFC Champions League Elite / J1 / Saudi Pro
 * League squads, and full rosters for the continental club cups (CAF
 * Champions League, Concacaf Champions Cup, Copa Libertadores). Domestic cup
 * rosters (FA Cup, Copa del Rey, etc.) and the second-tier continental cups
 * (Copa Sudamericana, AFC Champions League Two) run 30-125 entries deep into
 * lower divisions and amateur sides — those get a curated pass over the
 * clubs that are actually recognizable (top-two-tier pros, well-known
 * historic clubs), not an exhaustive one; deeper entries fall back to the
 * club's English/native name (see clubNameCn) rather than risk a wrong or
 * invented translation. Any match between two clubs already covered above
 * still gets the right name regardless of which competition it's in.
 */

export const CLUB_NAMES_CN: Record<string, string> = {
  // Premier League
  "AFC Bournemouth": "伯恩茅斯",
  Arsenal: "阿森纳",
  "Aston Villa": "阿斯顿维拉",
  Brentford: "布伦特福德",
  "Brighton & Hove Albion": "布莱顿",
  Chelsea: "切尔西",
  "Coventry City": "考文垂",
  "Crystal Palace": "水晶宫",
  Everton: "埃弗顿",
  Fulham: "富勒姆",
  "Hull City": "赫尔城",
  "Ipswich Town": "伊普斯维奇",
  "Leeds United": "利兹联",
  Liverpool: "利物浦",
  "Manchester City": "曼城",
  "Manchester United": "曼联",
  "Newcastle United": "纽卡斯尔联",
  "Nottingham Forest": "诺丁汉森林",
  Sunderland: "桑德兰",
  "Tottenham Hotspur": "托特纳姆热刺",

  // La Liga
  Alavés: "阿拉维斯",
  "Athletic Club": "毕尔巴鄂竞技",
  "Atlético Madrid": "马德里竞技",
  Barcelona: "巴塞罗那",
  "Celta Vigo": "塞尔塔",
  "Deportivo La Coruña": "拉科鲁尼亚",
  Elche: "埃尔切",
  Espanyol: "西班牙人",
  Getafe: "赫塔费",
  Levante: "莱万特",
  Málaga: "马拉加",
  Osasuna: "奥萨苏纳",
  "Racing Santander": "桑坦德竞技",
  "Rayo Vallecano": "巴列卡诺",
  "Real Betis": "皇家贝蒂斯",
  "Real Madrid": "皇家马德里",
  "Real Sociedad": "皇家社会",
  Sevilla: "塞维利亚",
  Valencia: "瓦伦西亚",
  Villarreal: "比利亚雷亚尔",

  // Bundesliga
  "1. FC Union Berlin": "柏林联合",
  "Bayer Leverkusen": "勒沃库森",
  "Bayern Munich": "拜仁慕尼黑",
  "Borussia Dortmund": "多特蒙德",
  "Borussia Mönchengladbach": "门兴格拉德巴赫",
  "Eintracht Frankfurt": "法兰克福",
  "FC Augsburg": "奥格斯堡",
  "FC Cologne": "科隆",
  "Hamburg SV": "汉堡",
  Mainz: "美因茨",
  "RB Leipzig": "莱比锡红牛",
  "SC Freiburg": "弗赖堡",
  "SC Paderborn 07": "帕德博恩",
  "SV Elversberg": "埃尔沃斯贝格",
  "Schalke 04": "沙尔克04",
  "TSG Hoffenheim": "霍芬海姆",
  "VfB Stuttgart": "斯图加特",
  "Werder Bremen": "云达不来梅",

  // Serie A
  "AC Milan": "AC米兰",
  "AS Roma": "罗马",
  Atalanta: "亚特兰大",
  Bologna: "博洛尼亚",
  Cagliari: "卡利亚里",
  Como: "科莫",
  Fiorentina: "佛罗伦萨",
  Frosinone: "弗罗西诺内",
  Genoa: "热那亚",
  Internazionale: "国际米兰",
  Juventus: "尤文图斯",
  Lazio: "拉齐奥",
  Lecce: "莱切",
  Monza: "蒙扎",
  Napoli: "那不勒斯",
  Parma: "帕尔马",
  Sassuolo: "萨索洛",
  Torino: "都灵",
  Udinese: "乌迪内斯",
  Venezia: "威尼斯",

  // Ligue 1
  "AJ Auxerre": "欧塞尔",
  "AS Monaco": "摩纳哥",
  Angers: "昂热",
  Brest: "布雷斯特",
  "Le Havre AC": "勒阿弗尔",
  "Le Mans": "勒芒",
  Lens: "朗斯",
  Lille: "里尔",
  Lorient: "洛里昂",
  Lyon: "里昂",
  Marseille: "马赛",
  Nice: "尼斯",
  "Paris FC": "巴黎FC",
  "Paris Saint-Germain": "巴黎圣日耳曼",
  "Stade Rennais": "雷恩",
  Strasbourg: "斯特拉斯堡",
  Toulouse: "图卢兹",
  Troyes: "特鲁瓦",

  // MLS
  "Atlanta United FC": "亚特兰大联",
  "Austin FC": "奥斯汀FC",
  "CF Montréal": "蒙特利尔CF",
  "Charlotte FC": "夏洛特FC",
  "Chicago Fire FC": "芝加哥火焰",
  "Colorado Rapids": "科罗拉多急流",
  "Columbus Crew": "哥伦布机员",
  "D.C. United": "华盛顿特区联",
  "FC Cincinnati": "辛辛那提FC",
  "FC Dallas": "达拉斯FC",
  "Houston Dynamo FC": "休斯顿迪纳摩",
  "Inter Miami CF": "迈阿密国际",
  "LA Galaxy": "洛杉矶银河",
  LAFC: "洛杉矶FC",
  "Minnesota United FC": "明尼苏达联",
  "Nashville SC": "纳什维尔SC",
  "New England Revolution": "新英格兰革命",
  "New York City FC": "纽约城",
  "Orlando City SC": "奥兰多城",
  "Philadelphia Union": "费城联合",
  "Portland Timbers": "波特兰伐木者",
  "Real Salt Lake": "皇家盐湖城",
  "Red Bull New York": "纽约红牛",
  "San Diego FC": "圣地亚哥FC",
  "San Jose Earthquakes": "圣何塞地震",
  "Seattle Sounders FC": "西雅图海湾人",
  "Sporting Kansas City": "堪萨斯城竞技",
  "St. Louis CITY SC": "圣路易斯城",
  "Toronto FC": "多伦多FC",
  "Vancouver Whitecaps": "温哥华白帽",

  // Liga MX
  América: "美洲",
  Atlante: "亚特兰特",
  Atlas: "阿特拉斯",
  "Atlético de San Luis": "圣路易斯竞技",
  "Cruz Azul": "蓝十字",
  "FC Juarez": "华雷斯FC",
  Guadalajara: "瓜达拉哈拉",
  León: "莱昂",
  Monterrey: "蒙特雷",
  Necaxa: "内卡萨",
  Pachuca: "帕丘卡",
  Puebla: "普埃布拉",
  "Pumas UNAM": "美洲狮",
  Querétaro: "克雷塔罗",
  "Tigres UANL": "老虎",
  Tijuana: "蒂华纳",
  Toluca: "托卢卡",

  // Brasileirão Série A
  "Athletico-PR": "巴拉那竞技",
  "Atlético-MG": "米内罗竞技",
  Bahia: "巴伊亚",
  Botafogo: "博塔弗戈",
  Chapecoense: "沙佩科恩斯",
  Corinthians: "科林蒂安",
  Coritiba: "库里蒂巴",
  Cruzeiro: "克鲁塞罗",
  Flamengo: "弗拉门戈",
  Fluminense: "弗鲁米嫩塞",
  Grêmio: "格雷米奥",
  Internacional: "国际",
  Mirassol: "米拉索尔",
  Palmeiras: "帕尔梅拉斯",
  "Red Bull Bragantino": "布拉干蒂诺红牛",
  Remo: "雷莫",
  Santos: "桑托斯",
  "São Paulo": "圣保罗",
  "Vasco da Gama": "瓦斯科达伽马",
  Vitória: "维多利亚",

  // Liga Profesional (Argentina)
  Aldosivi: "阿尔多西维",
  "Argentinos Juniors": "阿根廷青年人",
  "Atlético Tucumán": "图库曼竞技",
  Banfield: "班菲尔德",
  "Barracas Central": "巴拉卡斯中央",
  "Belgrano (Córdoba)": "贝尔格拉诺",
  "Boca Juniors": "博卡青年",
  "Central Córdoba (Santiago del Estero)": "圣地亚哥中央科尔多瓦",
  "Defensa y Justicia": "防卫司法",
  "Deportivo Riestra": "里耶斯特拉",
  "Estudiantes de La Plata": "拉普拉塔大学生",
  "Estudiantes de Río Cuarto": "里奥夸尔托大学生",
  "Gimnasia (Mendoza)": "门多萨体操",
  "Gimnasia La Plata": "拉普拉塔体操击剑",
  Huracán: "乌拉坎",
  Independiente: "独立队",
  "Independiente Rivadavia": "里瓦达维亚独立",
  "Instituto (Córdoba)": "因斯蒂图特",
  Lanús: "拉努斯",
  "Newell's Old Boys": "纽维尔老男孩",
  Platense: "普拉滕塞",
  "Racing Club": "拉辛俱乐部",
  "River Plate": "河床",
  "Rosario Central": "罗萨里奥中央",
  "San Lorenzo": "圣洛伦索",
  "Sarmiento (Junín)": "萨米恩托",
  "Talleres (Córdoba)": "塔列雷斯",
  Tigre: "蒂格雷",
  "Unión (Santa Fe)": "圣菲联盟",
  "Vélez Sarsfield": "贝莱斯萨斯菲尔德",

  // Chinese Super League — native names, not translations
  "Beijing Guoan": "北京国安",
  "Chengdu Rongcheng": "成都蓉城",
  "Chongqing Tonglianglong": "重庆铜梁龙",
  "Dalian Yingbo": "大连英博",
  Henan: "河南队",
  "Liaoning Tieren": "辽宁铁人",
  "Qingdao Hainiu": "青岛海牛",
  "Qingdao West Coast": "青岛西海岸",
  "Shandong Taishan": "山东泰山",
  "Shanghai Port": "上海海港",
  "Shanghai Shenhua": "上海申花",
  "Shenzhen Xinpengcheng": "深圳新鹏城",
  "Tianjin Jinmen Tiger": "天津津门虎",
  "Wuhan Three Towns": "武汉三镇",
  "Yunnan Yukun": "云南玉昆",
  "Zhejiang Professional FC": "浙江队",

  // UEFA Champions League (clubs not already covered by a domestic league above)
  "Ajax Amsterdam": "阿贾克斯",
  Benfica: "本菲卡",
  "Bodo/Glimt": "博德闪耀",
  "Club Brugge": "布鲁日",
  "F.C. København": "哥本哈根",
  "FK Qarabag": "卡拉巴赫",
  Galatasaray: "加拉塔萨雷",
  "Kairat Almaty": "凯拉特",
  "PSV Eindhoven": "埃因霍温",
  Pafos: "帕福斯",
  "Slavia Prague": "布拉格斯拉维亚",
  "Sporting CP": "里斯本竞技",
  "Union St.-Gilloise": "圣吉罗斯联",

  // UEFA Europa League (clubs not already covered above)
  Braga: "布拉加",
  Celtic: "凯尔特人",
  "Dinamo Zagreb": "萨格勒布迪纳摩",
  "FC Basel": "巴塞尔",
  "FC Midtjylland": "中日德兰",
  "FC Porto": "波尔图",
  "FC Utrecht": "乌得勒支",
  FCSB: "布加勒斯特星",
  Fenerbahce: "费内巴切",
  Ferencvaros: "费伦茨瓦罗斯",
  "Feyenoord Rotterdam": "费耶诺德",
  "Go Ahead Eagles": "前进鹰",
  "Ludogorets Razgrad": "卢多戈雷茨",
  "Maccabi Tel-Aviv": "特拉维夫马卡比",
  "Malmö FF": "马尔默",
  Olympiacos: "奥林匹亚科斯",
  PAOK: "帕奥克",
  Panathinaikos: "帕纳辛奈科斯",
  "RB Salzburg": "萨尔茨堡红牛",
  "Racing Genk": "亨克",
  Rangers: "流浪者",
  "Red Star Belgrade": "贝尔格莱德红星",
  "SK Brann": "布兰",
  "SK Sturm Graz": "格拉茨风暴",
  "Viktoria Plzen": "皮尔森胜利",
  "Young Boys": "伯尔尼年轻人",

  // Saudi Pro League
  Abha: "阿卜哈",
  "Al Ahli": "吉达阿赫利",
  "Al Diriyah": "迪利耶",
  "Al Ettifaq": "伊蒂法克",
  "Al Fateh": "法泰赫",
  "Al Fayha": "法伊哈",
  "Al Hazem": "哈兹姆",
  "Al Hilal": "利雅得新月",
  "Al Ittihad": "吉达联合",
  "Al Khaleej": "哈利吉",
  "Al Kholood": "库卢德",
  "Al Nassr": "利雅得胜利",
  "Al Qadsiah": "卡迪西亚",
  "Al Riyadh": "利雅得联",
  "Al Shabab": "利雅得青年人",
  "Al Taawoun": "塔阿翁",
  "Al-Faisaly": "费萨利",
  "Neom SC": "尼欧姆",

  // AFC Champions League Elite (clubs not already covered above)
  "Al Duhail": "杜海勒",
  "Al Gharafa": "加拉法",
  "Al Sadd": "萨德",
  "Al-Shorta": "警察俱乐部",
  "Al-Wahda": "瓦赫达",
  "Buriram United": "武里南联",
  "FC Seoul": "首尔FC",
  "Gangwon FC": "江原FC",
  "Johor Darul Ta'zim": "柔佛DT",
  "Melbourne City FC": "墨尔本城",
  "Nasaf Qarshi": "纳萨夫",
  "Shabab Al-Ahli": "沙巴布阿赫利",
  Sharjah: "沙迦",
  "Traktor Sazi FC": "大不里士拖拉机",
  "Ulsan HD": "蔚山HD",

  // J1 League (clubs not already covered above)
  "Avispa Fukuoka": "福冈黄蜂",
  "Cerezo Osaka": "大阪樱花",
  "FC Tokyo": "东京FC",
  "Fagiano Okayama": "冈山法基亚诺",
  "Gamba Osaka": "大阪飞脚",
  "JEF United Ichihara-Chiba": "千叶市原联合",
  "Kashima Antlers": "鹿岛鹿角",
  "Kashiwa Reysol": "柏太阳神",
  "Kawasaki Frontale": "川崎前锋",
  "Kyoto Sanga": "京都不死鸟",
  "Machida Zelvia": "町田泽维亚",
  "Mito Hollyhock": "水户蜀葵",
  "Nagoya Grampus": "名古屋鲸八",
  "Sanfrecce Hiroshima": "广岛三箭",
  "Shimizu S-Pulse": "清水心跳",
  "Tokyo Verdy 1969": "东京绿茵",
  "Urawa Red Diamonds": "浦和红钻",
  "V-Varen Nagasaki": "长崎水仙",
  "Vissel Kobe": "神户胜利船",
  "Yokohama F. Marinos": "横滨水手",

  // FA Cup — English Championship / notable League One clubs
  "Birmingham City": "伯明翰城",
  "Blackburn Rovers": "布莱克本流浪者",
  Blackpool: "黑池",
  "Bolton Wanderers": "博尔顿流浪者",
  "Bradford City": "布拉德福德城",
  "Bristol City": "布里斯托尔城",
  "Bristol Rovers": "布里斯托尔流浪者",
  Burnley: "伯恩利",
  "Cardiff City": "卡迪夫城",
  "Charlton Athletic": "查尔顿竞技",
  "Derby County": "德比郡",
  "Huddersfield Town": "哈德斯菲尔德",
  "Leicester City": "莱斯特城",
  "Luton Town": "卢顿",
  Middlesbrough: "米德尔斯堡",
  Millwall: "米尔沃尔",
  "Norwich City": "诺维奇",
  "Oxford United": "牛津联",
  "Peterborough United": "彼得堡联",
  "Plymouth Argyle": "普利茅斯",
  Portsmouth: "朴茨茅斯",
  "Preston North End": "普雷斯顿",
  "Queens Park Rangers": "女王公园巡游者",
  Reading: "雷丁",
  "Rotherham United": "罗瑟汉姆联",
  "Sheffield United": "谢菲尔德联",
  "Sheffield Wednesday": "谢菲尔德星期三",
  Southampton: "南安普顿",
  "Southend United": "索思恩德联",
  "Stoke City": "斯托克城",
  "Swansea City": "斯旺西城",
  "Swindon Town": "斯温登镇",
  Watford: "沃特福德",
  "West Bromwich Albion": "西布罗姆维奇",
  "West Ham United": "西汉姆联",
  "Wigan Athletic": "维根竞技",
  "Wolverhampton Wanderers": "狼队",
  Wrexham: "雷克瑟姆",

  // Copa del Rey — Spanish Segunda / notable clubs
  Almería: "阿尔梅里亚",
  Burgos: "布尔戈斯",
  Cádiz: "加的斯",
  Córdoba: "科尔多瓦",
  "Cultural Leonesa": "莱昂文化",
  Eibar: "埃瓦尔",
  "FC Andorra": "安道尔人",
  Girona: "赫罗纳",
  Granada: "格拉纳达",
  Huesca: "韦斯卡",
  "Las Palmas": "拉斯帕尔马斯",
  Leganés: "莱加内斯",
  Mallorca: "马略卡",
  Mirandés: "米兰德斯",
  Numancia: "努曼西亚",
  Ponferradina: "蓬费拉迪纳",
  "Real Oviedo": "皇家奥维耶多",
  "Real Valladolid": "皇家瓦拉多利德",
  "Real Zaragoza": "皇家萨拉戈萨",
  "Sporting Gijón": "希红体育",
  Tenerife: "特内里费",
  "UD Ibiza": "伊维萨",
  "UCAM Murcia": "穆尔西亚UCAM",

  // DFB-Pokal — German 2. Bundesliga / notable clubs
  "1. FC Nürnberg": "纽伦堡",
  "1. FC Magdeburg": "马格德堡",
  "Arminia Bielefeld": "比勒费尔德竞技",
  "Dynamo Dresden": "德累斯顿迪纳摩",
  "Fortuna Düsseldorf": "杜塞尔多夫",
  "Hannover 96": "汉诺威96",
  "Hansa Rostock": "罗斯托克汉萨",
  "Hertha Berlin": "柏林赫塔",
  "Holstein Kiel": "基尔",
  Kaiserslautern: "凯泽斯劳滕",
  "Karlsruher SC": "卡尔斯鲁厄",
  "MSV Duisburg": "杜伊斯堡",
  "St. Pauli": "圣保利",
  "SpVgg Greuther Fürth": "菲尔特",
  "TSV 1860 Munich": "慕尼黑1860",
  "VfL Bochum": "波鸿",
  "VfL Wolfsburg": "沃尔夫斯堡",

  // Coppa Italia — Serie B / notable clubs
  Benevento: "贝内文托",
  Catania: "卡塔尼亚",
  Cesena: "切塞纳",
  Cremonese: "克雷莫纳",
  Empoli: "恩波利",
  "Hellas Verona": "维罗纳",
  Palermo: "巴勒莫",
  Pisa: "比萨",
  Sampdoria: "桑普多利亚",

  // Coupe de France — Ligue 2 / notable clubs
  Bordeaux: "波尔多",
  Guingamp: "甘冈",
  Metz: "梅斯",
  Montpellier: "蒙彼利埃",
  Nantes: "南特",
  "Saint-Étienne": "圣埃蒂安",
  Sochaux: "索肖",
  "Stade de Reims": "兰斯",

  // U.S. Open Cup — notable lower-division clubs beyond MLS
  "Louisville City FC": "路易斯维尔城",
  "Phoenix Rising FC": "凤凰城崛起",
  "Sacramento Republic FC": "萨克拉门托共和国",
  "Detroit City FC": "底特律城",
  "Rhode Island FC": "罗德岛FC",
  "Indy Eleven": "印第安纳波利斯11人",

  // Copa Argentina — notable clubs beyond the top flight
  "Atletico Rafaela": "拉法埃拉竞技",
  "Godoy Cruz Antonio Tomba": "戈多伊克鲁斯",

  // Copa do Brasil — traditional / Série B clubs
  "América Mineiro": "美洲矿工",
  Avaí: "阿瓦伊",
  Ceará: "塞阿拉",
  CRB: "CRB",
  CSA: "CSA",
  Confiança: "孔菲安萨",
  Figueirense: "菲盖伦斯",
  Fortaleza: "福塔莱萨",
  Goiás: "戈亚斯",
  Guarani: "瓜拉尼",
  Joinville: "儒安维利",
  Juventude: "尤文图德",
  Londrina: "隆德里纳",
  "Nova Iguaçu": "新伊瓜苏",
  Novorizontino: "诺沃里宗蒂诺",
  Paysandu: "帕伊桑杜",
  "Ponte Preta": "蓬蒂普雷塔",
  Portuguesa: "葡萄牙人",
  "Sampaio Correa RJ": "桑派奥科雷亚",
  "Santa Cruz": "圣克鲁斯",
  Sport: "累西腓体育",
  Tombense: "通本斯",
  "Vila Nova": "维拉诺瓦",
  "Volta Redonda": "沃尔塔雷东达",

  // Copa MX — notable clubs beyond Liga MX
  "Alebrijes de Oaxaca": "瓦哈卡幻兽",
  Celaya: "塞拉亚",
  "Club Atlético Morelia": "莫雷利亚竞技",
  "Correcaminos UAT": "路跑者",
  "Leones Negros": "黑狮",
  "Mineros de Zacatecas": "萨卡特卡斯矿工",

  // CAF Champions League
  "AS FAR": "FAR拉巴特",
  "Al Ahly": "开罗国民",
  "Al Hilal Omdurman": "恩图曼希拉尔",
  "Esperance Sportive de Tunis": "突尼斯希望",
  "FC Saint Eloi Lupopo": "卢波波圣埃卢瓦",
  "JS Kabylie": "卡比利亚青年",
  "MC Alger": "阿尔及尔竞技",
  "Mamelodi Sundowns": "马梅隆迪日落",
  "Petro de Luanda": "罗安达石油",
  "Power Dynamos": "电力发电机",
  "Pyramids FC": "金字塔",
  "RSB Berkane": "贝尔卡内联盟",
  "Rivers United FC": "河流联",
  "Simba SC": "辛巴",
  "Stade Malien": "马里体育会",
  "Young Africans": "非洲青年",

  // Concacaf Champions Cup — clubs not already covered above
  Alajuelense: "阿拉胡埃拉体育",
  "Atlético Ottawa": "渥太华竞技",
  Cartaginés: "卡塔戈",
  "Club Deportivo Olimpia": "奥林匹亚",
  "Defense Force FC": "防卫部队",
  "Forge FC": "铸造",
  "Mount Pleasant FA": "芒特普莱森特",
  "Real España": "雷阿尔埃斯帕尼亚",
  "Sporting San Miguelito": "圣米格利托竞技",
  "Universidad O&M": "奥马大学",
  "Vancouver FC": "温哥华FC",
  "Xelajú MC": "克萨尔特南戈",

  // CONMEBOL Libertadores — clubs not already covered above
  "2 de Mayo": "五月二日",
  "Always Ready": "永远准备",
  "Atlético Junior": "巴兰基亚初级人",
  "Barcelona SC": "巴萨罗那竞技",
  Bolívar: "博利瓦尔",
  Carabobo: "卡拉沃沃",
  "Cerro Porteño": "塞罗波尔特尼奥",
  "Coquimbo Unido": "科金博联合",
  "Cusco FC": "库斯科FC",
  "Deportes Tolima": "托利马体育",
  "Deportivo La Guaira": "拉瓜伊拉竞技",
  "Deportivo Táchira": "塔奇拉竞技",
  Guaraní: "瓜拉尼(巴拉圭)",
  Huachipato: "瓦查帕托",
  "Independiente Medellín": "麦德林独立",
  "Independiente Santa Fe": "圣菲独立",
  "Independiente del Valle": "山谷独立",
  Juventud: "青年人(乌拉圭)",
  Libertad: "自由队",
  "Liga de Quito": "基多利加",
  Nacional: "蒙得维的亚民族",
  "Nacional Potosí": "波托西民族",
  "O'Higgins": "奥伊金斯",
  Peñarol: "佩纳罗尔",
  "Sporting Cristal": "水晶体育",
  "UCV FC": "中央大学FC",
  "Universidad Católica": "天主教大学",
  Universitario: "大学生队",

  // CONMEBOL Sudamericana — clubs not already covered above
  "América de Cali": "阿美利加",
  "Atlético Nacional": "国民竞技",
  "Caracas FC": "加拉加斯",
  "Club Olimpia": "奥林匹亚",
  "Defensor Sporting": "防卫体育",
  "Libertad (Ecuador)": "自由队(厄瓜多尔)",
  Melgar: "梅尔加",
  Millonarios: "百万富翁",
  "Nacional Asunción": "亚松森民族",
  Palestino: "智利巴勒斯坦人",
  "Racing (Montevideo)": "蒙得维的亚竞赛",
  "Universidad de Chile": "智利大学",

  // AFC Champions League Two (afc.cup) — notable clubs beyond what's covered above
  "Mohun Bagan Super Giant": "莫罕巴干",
  Persib: "佩尔西布万隆",
  "Pohang Steelers": "浦项制铁",
  "FC Goa": "果阿",
  "Al Wasl": "瓦斯尔",
  "Bangkok United": "曼谷联合",
  "Cong An Hanoi": "河内公安",
  Esteghlal: "德黑兰独立",
  "Lion City Sailors FC": "狮城水手",
  "Nam Dinh": "南定",
  "Selangor FC": "雪兰莪",
  Sepahan: "塞帕汗",
  "Tai Po FC": "大埔",

  // Clubs spotted in preseason/friendly fixtures, not otherwise covered above
  Trabzonspor: "特拉布宗体育",
  "FC Volendam": "沃伦丹",
  "Jeju United": "济州联",
};

/**
 * Overrides for names that mean different clubs in different competitions
 * (e.g. "Santos" is both Brazil's Santos FC and Mexico's Santos Laguna).
 * Keyed by `${leagueCode}:${displayName}`; checked before the flat map above.
 */
const LEAGUE_OVERRIDES: Record<string, string> = {
  "mex.1:Santos": "桑托斯拉古纳",
  "mex.copa_mx:Santos": "桑托斯拉古纳",
  "conmebol.libertadores:Liverpool": "利物浦蒙得维的亚",
};

/** Looks up a club's Chinese name; returns undefined if not in the curated list. */
export function clubNameCn(leagueCode: string, displayName: string): string | undefined {
  return LEAGUE_OVERRIDES[`${leagueCode}:${displayName}`] ?? CLUB_NAMES_CN[displayName];
}
