/**
 * Curated Chinese names for clubs in the leagues tracked by
 * lib/daily-fetcher.ts (Premier League, La Liga, Bundesliga, Serie A,
 * Ligue 1, MLS, Liga MX, Brasileirão, Argentine Liga Profesional, and the
 * Chinese Super League).
 *
 * Keyed by `${leagueCode}:${ESPN displayName}` — a couple of club names
 * repeat across leagues with different real clubs behind them (e.g. "Santos"
 * is both Brazil's Santos FC and Mexico's Santos Laguna), so the league code
 * disambiguates rather than risking a wrong name from a flat lookup.
 *
 * CSL entries are each club's native Chinese name (not a translation).
 * Everything else uses the name in common use by Chinese-language football
 * media. Coverage is each league's current squad as of when this was
 * written — a promoted/relegated or newly formed club may not have an entry
 * yet, so lookups should fall back to the English name (see clubNameCn).
 */

export const CLUB_NAMES_CN: Record<string, string> = {
  // Premier League (eng.1)
  "eng.1:AFC Bournemouth": "伯恩茅斯",
  "eng.1:Arsenal": "阿森纳",
  "eng.1:Aston Villa": "阿斯顿维拉",
  "eng.1:Brentford": "布伦特福德",
  "eng.1:Brighton & Hove Albion": "布莱顿",
  "eng.1:Chelsea": "切尔西",
  "eng.1:Coventry City": "考文垂",
  "eng.1:Crystal Palace": "水晶宫",
  "eng.1:Everton": "埃弗顿",
  "eng.1:Fulham": "富勒姆",
  "eng.1:Hull City": "赫尔城",
  "eng.1:Ipswich Town": "伊普斯维奇",
  "eng.1:Leeds United": "利兹联",
  "eng.1:Liverpool": "利物浦",
  "eng.1:Manchester City": "曼城",
  "eng.1:Manchester United": "曼联",
  "eng.1:Newcastle United": "纽卡斯尔联",
  "eng.1:Nottingham Forest": "诺丁汉森林",
  "eng.1:Sunderland": "桑德兰",
  "eng.1:Tottenham Hotspur": "托特纳姆热刺",

  // La Liga (esp.1)
  "esp.1:Alavés": "阿拉维斯",
  "esp.1:Athletic Club": "毕尔巴鄂竞技",
  "esp.1:Atlético Madrid": "马德里竞技",
  "esp.1:Barcelona": "巴塞罗那",
  "esp.1:Celta Vigo": "塞尔塔",
  "esp.1:Deportivo La Coruña": "拉科鲁尼亚",
  "esp.1:Elche": "埃尔切",
  "esp.1:Espanyol": "西班牙人",
  "esp.1:Getafe": "赫塔费",
  "esp.1:Levante": "莱万特",
  "esp.1:Málaga": "马拉加",
  "esp.1:Osasuna": "奥萨苏纳",
  "esp.1:Racing Santander": "桑坦德竞技",
  "esp.1:Rayo Vallecano": "巴列卡诺",
  "esp.1:Real Betis": "皇家贝蒂斯",
  "esp.1:Real Madrid": "皇家马德里",
  "esp.1:Real Sociedad": "皇家社会",
  "esp.1:Sevilla": "塞维利亚",
  "esp.1:Valencia": "瓦伦西亚",
  "esp.1:Villarreal": "比利亚雷亚尔",

  // Bundesliga (ger.1)
  "ger.1:1. FC Union Berlin": "柏林联合",
  "ger.1:Bayer Leverkusen": "勒沃库森",
  "ger.1:Bayern Munich": "拜仁慕尼黑",
  "ger.1:Borussia Dortmund": "多特蒙德",
  "ger.1:Borussia Mönchengladbach": "门兴格拉德巴赫",
  "ger.1:Eintracht Frankfurt": "法兰克福",
  "ger.1:FC Augsburg": "奥格斯堡",
  "ger.1:FC Cologne": "科隆",
  "ger.1:Hamburg SV": "汉堡",
  "ger.1:Mainz": "美因茨",
  "ger.1:RB Leipzig": "莱比锡红牛",
  "ger.1:SC Freiburg": "弗赖堡",
  "ger.1:SC Paderborn 07": "帕德博恩",
  "ger.1:SV Elversberg": "埃尔沃斯贝格",
  "ger.1:Schalke 04": "沙尔克04",
  "ger.1:TSG Hoffenheim": "霍芬海姆",
  "ger.1:VfB Stuttgart": "斯图加特",
  "ger.1:Werder Bremen": "云达不来梅",

  // Serie A (ita.1)
  "ita.1:AC Milan": "AC米兰",
  "ita.1:AS Roma": "罗马",
  "ita.1:Atalanta": "亚特兰大",
  "ita.1:Bologna": "博洛尼亚",
  "ita.1:Cagliari": "卡利亚里",
  "ita.1:Como": "科莫",
  "ita.1:Fiorentina": "佛罗伦萨",
  "ita.1:Frosinone": "弗罗西诺内",
  "ita.1:Genoa": "热那亚",
  "ita.1:Internazionale": "国际米兰",
  "ita.1:Juventus": "尤文图斯",
  "ita.1:Lazio": "拉齐奥",
  "ita.1:Lecce": "莱切",
  "ita.1:Monza": "蒙扎",
  "ita.1:Napoli": "那不勒斯",
  "ita.1:Parma": "帕尔马",
  "ita.1:Sassuolo": "萨索洛",
  "ita.1:Torino": "都灵",
  "ita.1:Udinese": "乌迪内斯",
  "ita.1:Venezia": "威尼斯",

  // Ligue 1 (fra.1)
  "fra.1:AJ Auxerre": "欧塞尔",
  "fra.1:AS Monaco": "摩纳哥",
  "fra.1:Angers": "昂热",
  "fra.1:Brest": "布雷斯特",
  "fra.1:Le Havre AC": "勒阿弗尔",
  "fra.1:Le Mans": "勒芒",
  "fra.1:Lens": "朗斯",
  "fra.1:Lille": "里尔",
  "fra.1:Lorient": "洛里昂",
  "fra.1:Lyon": "里昂",
  "fra.1:Marseille": "马赛",
  "fra.1:Nice": "尼斯",
  "fra.1:Paris FC": "巴黎FC",
  "fra.1:Paris Saint-Germain": "巴黎圣日耳曼",
  "fra.1:Stade Rennais": "雷恩",
  "fra.1:Strasbourg": "斯特拉斯堡",
  "fra.1:Toulouse": "图卢兹",
  "fra.1:Troyes": "特鲁瓦",

  // MLS (usa.1)
  "usa.1:Atlanta United FC": "亚特兰大联",
  "usa.1:Austin FC": "奥斯汀FC",
  "usa.1:CF Montréal": "蒙特利尔CF",
  "usa.1:Charlotte FC": "夏洛特FC",
  "usa.1:Chicago Fire FC": "芝加哥火焰",
  "usa.1:Colorado Rapids": "科罗拉多急流",
  "usa.1:Columbus Crew": "哥伦布机员",
  "usa.1:D.C. United": "华盛顿特区联",
  "usa.1:FC Cincinnati": "辛辛那提FC",
  "usa.1:FC Dallas": "达拉斯FC",
  "usa.1:Houston Dynamo FC": "休斯顿迪纳摩",
  "usa.1:Inter Miami CF": "迈阿密国际",
  "usa.1:LA Galaxy": "洛杉矶银河",
  "usa.1:LAFC": "洛杉矶FC",
  "usa.1:Minnesota United FC": "明尼苏达联",
  "usa.1:Nashville SC": "纳什维尔SC",
  "usa.1:New England Revolution": "新英格兰革命",
  "usa.1:New York City FC": "纽约城",
  "usa.1:Orlando City SC": "奥兰多城",
  "usa.1:Philadelphia Union": "费城联合",
  "usa.1:Portland Timbers": "波特兰伐木者",
  "usa.1:Real Salt Lake": "皇家盐湖城",
  "usa.1:Red Bull New York": "纽约红牛",
  "usa.1:San Diego FC": "圣地亚哥FC",
  "usa.1:San Jose Earthquakes": "圣何塞地震",
  "usa.1:Seattle Sounders FC": "西雅图海湾人",
  "usa.1:Sporting Kansas City": "堪萨斯城竞技",
  "usa.1:St. Louis CITY SC": "圣路易斯城",
  "usa.1:Toronto FC": "多伦多FC",
  "usa.1:Vancouver Whitecaps": "温哥华白帽",

  // Liga MX (mex.1)
  "mex.1:América": "美洲",
  "mex.1:Atlante": "亚特兰特",
  "mex.1:Atlas": "阿特拉斯",
  "mex.1:Atlético de San Luis": "圣路易斯竞技",
  "mex.1:Cruz Azul": "蓝十字",
  "mex.1:FC Juarez": "华雷斯FC",
  "mex.1:Guadalajara": "瓜达拉哈拉",
  "mex.1:León": "莱昂",
  "mex.1:Monterrey": "蒙特雷",
  "mex.1:Necaxa": "内卡萨",
  "mex.1:Pachuca": "帕丘卡",
  "mex.1:Puebla": "普埃布拉",
  "mex.1:Pumas UNAM": "美洲狮",
  "mex.1:Querétaro": "克雷塔罗",
  "mex.1:Santos": "桑托斯拉古纳",
  "mex.1:Tigres UANL": "老虎",
  "mex.1:Tijuana": "蒂华纳",
  "mex.1:Toluca": "托卢卡",

  // Brasileirão Série A (bra.1)
  "bra.1:Athletico-PR": "巴拉那竞技",
  "bra.1:Atlético-MG": "米内罗竞技",
  "bra.1:Bahia": "巴伊亚",
  "bra.1:Botafogo": "博塔弗戈",
  "bra.1:Chapecoense": "沙佩科恩斯",
  "bra.1:Corinthians": "科林蒂安",
  "bra.1:Coritiba": "库里蒂巴",
  "bra.1:Cruzeiro": "克鲁塞罗",
  "bra.1:Flamengo": "弗拉门戈",
  "bra.1:Fluminense": "弗鲁米嫩塞",
  "bra.1:Grêmio": "格雷米奥",
  "bra.1:Internacional": "国际",
  "bra.1:Mirassol": "米拉索尔",
  "bra.1:Palmeiras": "帕尔梅拉斯",
  "bra.1:Red Bull Bragantino": "布拉干蒂诺红牛",
  "bra.1:Remo": "雷莫",
  "bra.1:Santos": "桑托斯",
  "bra.1:São Paulo": "圣保罗",
  "bra.1:Vasco da Gama": "瓦斯科达伽马",
  "bra.1:Vitória": "维多利亚",

  // Liga Profesional (Argentina) (arg.1)
  "arg.1:Aldosivi": "阿尔多西维",
  "arg.1:Argentinos Juniors": "阿根廷青年人",
  "arg.1:Atlético Tucumán": "图库曼竞技",
  "arg.1:Banfield": "班菲尔德",
  "arg.1:Barracas Central": "巴拉卡斯中央",
  "arg.1:Belgrano (Córdoba)": "贝尔格拉诺",
  "arg.1:Boca Juniors": "博卡青年",
  "arg.1:Central Córdoba (Santiago del Estero)": "圣地亚哥中央科尔多瓦",
  "arg.1:Defensa y Justicia": "防卫司法",
  "arg.1:Deportivo Riestra": "里耶斯特拉",
  "arg.1:Estudiantes de La Plata": "拉普拉塔大学生",
  "arg.1:Estudiantes de Río Cuarto": "里奥夸尔托大学生",
  "arg.1:Gimnasia (Mendoza)": "门多萨体操",
  "arg.1:Gimnasia La Plata": "拉普拉塔体操击剑",
  "arg.1:Huracán": "乌拉坎",
  "arg.1:Independiente": "独立队",
  "arg.1:Independiente Rivadavia": "里瓦达维亚独立",
  "arg.1:Instituto (Córdoba)": "因斯蒂图特",
  "arg.1:Lanús": "拉努斯",
  "arg.1:Newell's Old Boys": "纽维尔老男孩",
  "arg.1:Platense": "普拉滕塞",
  "arg.1:Racing Club": "拉辛俱乐部",
  "arg.1:River Plate": "河床",
  "arg.1:Rosario Central": "罗萨里奥中央",
  "arg.1:San Lorenzo": "圣洛伦索",
  "arg.1:Sarmiento (Junín)": "萨米恩托",
  "arg.1:Talleres (Córdoba)": "塔列雷斯",
  "arg.1:Tigre": "蒂格雷",
  "arg.1:Unión (Santa Fe)": "圣菲联盟",
  "arg.1:Vélez Sarsfield": "贝莱斯萨斯菲尔德",

  // Chinese Super League (chn.1) — native names, not translations
  "chn.1:Beijing Guoan": "北京国安",
  "chn.1:Chengdu Rongcheng": "成都蓉城",
  "chn.1:Chongqing Tonglianglong": "重庆铜梁龙",
  "chn.1:Dalian Yingbo": "大连英博",
  "chn.1:Henan": "河南队",
  "chn.1:Liaoning Tieren": "辽宁铁人",
  "chn.1:Qingdao Hainiu": "青岛海牛",
  "chn.1:Qingdao West Coast": "青岛西海岸",
  "chn.1:Shandong Taishan": "山东泰山",
  "chn.1:Shanghai Port": "上海海港",
  "chn.1:Shanghai Shenhua": "上海申花",
  "chn.1:Shenzhen Xinpengcheng": "深圳新鹏城",
  "chn.1:Tianjin Jinmen Tiger": "天津津门虎",
  "chn.1:Wuhan Three Towns": "武汉三镇",
  "chn.1:Yunnan Yukun": "云南玉昆",
  "chn.1:Zhejiang Professional FC": "浙江队",
};

/** Looks up a club's Chinese name; returns undefined if not in the curated list. */
export function clubNameCn(leagueCode: string, displayName: string): string | undefined {
  return CLUB_NAMES_CN[`${leagueCode}:${displayName}`];
}
