/**
 * National team names → Chinese. Originally just the 48 FIFA World Cup 2026
 * teams (for CCTV / Migu search queries); extended to cover the national
 * teams appearing in the continental competitions tracked by
 * lib/daily-fetcher.ts (UEFA Euro, UEFA Nations League, Copa América, Africa
 * Cup of Nations, AFC Asian Cup, CONCACAF Gold Cup, CONCACAF Nations League).
 *
 * A few competitions spell the same country differently from the WC26
 * fixture list (e.g. "Bosnia-Herzegovina" vs "Bosnia and Herzegovina",
 * "Congo DR" vs "DR Congo", "South Korea" vs "Korea Republic") — both
 * spellings are included so lookups succeed regardless of source.
 */
export const TEAM_NAMES_CN: Record<string, string> = {
  Algeria: "阿尔及利亚",
  Argentina: "阿根廷",
  Australia: "澳大利亚",
  Austria: "奥地利",
  Belgium: "比利时",
  "Bosnia and Herzegovina": "波黑",
  Brazil: "巴西",
  Canada: "加拿大",
  "Cape Verde": "佛得角",
  Colombia: "哥伦比亚",
  Croatia: "克罗地亚",
  Curaçao: "库拉索",
  Czechia: "捷克",
  "DR Congo": "刚果民主共和国",
  Ecuador: "厄瓜多尔",
  Egypt: "埃及",
  England: "英格兰",
  France: "法国",
  Germany: "德国",
  Ghana: "加纳",
  Haiti: "海地",
  Iran: "伊朗",
  Iraq: "伊拉克",
  "Ivory Coast": "科特迪瓦",
  Japan: "日本",
  Jordan: "约旦",
  "Korea Republic": "韩国",
  Mexico: "墨西哥",
  Morocco: "摩洛哥",
  Netherlands: "荷兰",
  "New Zealand": "新西兰",
  Norway: "挪威",
  Panama: "巴拿马",
  Paraguay: "巴拉圭",
  Portugal: "葡萄牙",
  Qatar: "卡塔尔",
  "Saudi Arabia": "沙特阿拉伯",
  Scotland: "苏格兰",
  Senegal: "塞内加尔",
  "South Africa": "南非",
  Spain: "西班牙",
  Sweden: "瑞典",
  Switzerland: "瑞士",
  Tunisia: "突尼斯",
  Türkiye: "土耳其",
  "United States": "美国",
  Uruguay: "乌拉圭",
  Uzbekistan: "乌兹别克斯坦",

  // Added for continental national-team competitions (Euro, Nations
  // Leagues, Copa América, AFCON, Asian Cup, Gold Cup)
  Albania: "阿尔巴尼亚",
  Andorra: "安道尔",
  Angola: "安哥拉",
  "Antigua and Barbuda": "安提瓜和巴布达",
  Armenia: "亚美尼亚",
  Aruba: "阿鲁巴",
  Azerbaijan: "阿塞拜疆",
  Bahamas: "巴哈马",
  Bahrain: "巴林",
  Barbados: "巴巴多斯",
  Belarus: "白俄罗斯",
  Belize: "伯利兹",
  Benin: "贝宁",
  Bermuda: "百慕大",
  Bolivia: "玻利维亚",
  Bonaire: "博纳尔",
  "Bosnia-Herzegovina": "波黑",
  Botswana: "博茨瓦纳",
  "British Virgin Islands": "英属维尔京群岛",
  Bulgaria: "保加利亚",
  "Burkina Faso": "布基纳法索",
  Cameroon: "喀麦隆",
  "Cayman Islands": "开曼群岛",
  Chile: "智利",
  China: "中国",
  Comoros: "科摩罗",
  "Congo DR": "刚果民主共和国",
  "Costa Rica": "哥斯达黎加",
  Cuba: "古巴",
  Cyprus: "塞浦路斯",
  Denmark: "丹麦",
  Dominica: "多米尼克",
  "Dominican Republic": "多米尼加",
  "El Salvador": "萨尔瓦多",
  "Equatorial Guinea": "赤道几内亚",
  Estonia: "爱沙尼亚",
  "Faroe Islands": "法罗群岛",
  Finland: "芬兰",
  "French Guiana": "法属圭亚那",
  Gabon: "加蓬",
  Georgia: "格鲁吉亚",
  Gibraltar: "直布罗陀",
  Greece: "希腊",
  Grenada: "格林纳达",
  Guadeloupe: "瓜德罗普",
  Guatemala: "危地马拉",
  Guyana: "圭亚那",
  Honduras: "洪都拉斯",
  Hungary: "匈牙利",
  Iceland: "冰岛",
  Indonesia: "印度尼西亚",
  Israel: "以色列",
  Italy: "意大利",
  Jamaica: "牙买加",
  Kazakhstan: "哈萨克斯坦",
  Kosovo: "科索沃",
  Kuwait: "科威特",
  "Kyrgyz Republic": "吉尔吉斯斯坦",
  Latvia: "拉脱维亚",
  Liechtenstein: "列支敦士登",
  Lithuania: "立陶宛",
  Luxembourg: "卢森堡",
  Mali: "马里",
  Malta: "马耳他",
  Martinique: "马提尼克",
  Moldova: "摩尔多瓦",
  Montenegro: "黑山",
  Montserrat: "蒙特塞拉特",
  Mozambique: "莫桑比克",
  Nicaragua: "尼加拉瓜",
  "North Korea": "朝鲜",
  "North Macedonia": "北马其顿",
  "Northern Ireland": "北爱尔兰",
  Oman: "阿曼",
  Palestine: "巴勒斯坦",
  Peru: "秘鲁",
  Poland: "波兰",
  "Puerto Rico": "波多黎各",
  "Republic of Ireland": "爱尔兰",
  Romania: "罗马尼亚",
  "San Marino": "圣马力诺",
  Serbia: "塞尔维亚",
  Singapore: "新加坡",
  "Sint Maarten": "荷属圣马丁",
  Slovakia: "斯洛伐克",
  Slovenia: "斯洛文尼亚",
  "South Korea": "韩国",
  "St. Kitts and Nevis": "圣基茨和尼维斯",
  "St. Lucia": "圣卢西亚",
  "St. Martin": "法属圣马丁",
  "St. Vincent and the Grenadines": "圣文森特和格林纳丁斯",
  Sudan: "苏丹",
  Suriname: "苏里南",
  Syria: "叙利亚",
  Tajikistan: "塔吉克斯坦",
  Tanzania: "坦桑尼亚",
  Thailand: "泰国",
  "Trinidad and Tobago": "特立尼达和多巴哥",
  "Turks and Caicos Islands": "特克斯和凯科斯群岛",
  Uganda: "乌干达",
  Ukraine: "乌克兰",
  "United Arab Emirates": "阿拉伯联合酋长国",
  "US Virgin Islands": "美属维尔京群岛",
  Venezuela: "委内瑞拉",
  Vietnam: "越南",
  Wales: "威尔士",
  Yemen: "也门",
  Zambia: "赞比亚",
  Zimbabwe: "津巴布韦",
};

export function teamNameCn(team: string): string {
  return TEAM_NAMES_CN[team] ?? team;
}
